services:
  n8n:
    container_name: n8n-hackaton-2025
    build:
      context: .
      dockerfile: Dockerfile.custom
    env_file:
      - ./.env
    environment:
      - N8N_TRUST_PROXY=private_network
      - DB_SQLITE_POOL_SIZE=10
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n
            # Mount local bee2bee-indexer for development
      - ../../bee2bee-indexer-repo:/bee2bee-indexer-repo

volumes:
  n8n_data:
